### ISSUE TITLE
Bookmark + not working menu

### ISSUE THREAD

**Issue by krzychukula** [rgarcia/dochub#16]
Hello, I have issues with site.

1: when run from bookmark I can see only input. (changed to http://dochub.io/ as workaround)
2: Now when I click on Menu button nothing happens.
(console.log)

Failed to load resource
router.js:123Creating route for css
router.js:123Creating route for html
router.js:123Creating route for javascript
router.js:123Creating route for dom
router.js:123Creating route for jquery
router.js:123Creating route for php
router.js:123Creating route for python
router.js:156Setting language to css
languageview.js:79[setActive: CSS = true.]
languageview.js:26[Rendering CSS.]
languageview.js:92[Fetching CSS.]
fullwindow.js:23[Window height: 479.]
GET http://dochub.io/img/glyphicons-halflings.png 404 (Not Found)
2searchresults.js:37[Data loaded, rendering models.]
fullwindow.js:23[Window height: 479.]
languageview.js:98[Success fetching CSS.]
GET http://dochub.io/skins/common/icons/icon-trans.gif 404 (Not Found)
18event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.

for every click: event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.

**Comment by krzychukula** [comment]
When I gen only input in console I can see only:

Creating route for css
router.js:123Creating route for html
router.js:123Creating route for javascript
router.js:123Creating route for dom
router.js:123Creating route for jquery
router.js:123Creating route for php
router.js:123Creating route for python

Tried Ctrl+R, disabling Cache without success. 

I use chrome on Linux Mint, but I get those problem on windows 7 as well at work.

**Comment by yonran** [comment]
Probably #18 will fix this issue.

**Comment by krzychukula** [comment]
Looks ok. Thanks!
