### ISSUE TITLE
Debounce auto-search

### ISSUE THREAD

**Issue by indexzero** [rgarcia/dochub#24]
When I start typing there is a noticable freeze (especially a single letter). Perhaps you can debounce the search based on time or the length of the string?

**Comment by rgarcia** [comment]
we already debounce 100ms minimum (more for bigger doc sets)

check out https://github.com/rgarcia/dochub/blob/master/static/js/views/searchheader.js#L7

**Comment by indexzero** [comment]
I see. The lag I'm seeing (which is more than 100ms) is probably due to executing the search on single character searches. Maybe dont start searching until two characters?

**Comment by rgarcia** [comment]
interesting idea. My hunch is that the search itself is quick, and it's the DOM rendering that is slow. Some cap on the result set, or ideally some kind of infinite scroll+pagination would probably be ideal in terms of minimizing DOM load.
