### ISSUE TITLE
How to find attributes ?

### ISSUE THREAD

**Issue by Interned** [rgarcia/dochub#30]
Hi,

I'm testing your website and I like how you used the basic Boostrap template to build a doc center for helping developpers in their work.

But maybe some improvement should be released, like HTML attributes. They cruelly miss ! I mean they can't even be found by  the search engine.

Will that issue be resolved soon ?

**Comment by kevinburke** [comment]
Hi,
You should be able to view attributes for any HTML element by browsing to the element page and then checking the "Attributes" section. For example to see all of the attributes for the img tag, see http://dochub.io/#html/img.

**Comment by Interned** [comment]
Yep, that's the solution, I found it out. Thx.

**Comment by Interned** [comment]
Hi,

Sorry for answering so latetly : I get it, ofc these attributes can be
found by checking the "Attributes" section.

Sorry for my useless question and thanks a lot for your reply

Best regards,

Thomas

2012/10/21 Kevin Burke notifications@github.com
