### ISSUE TITLE
CSS - no :after, :before, :first-letter...

### ISSUE THREAD

**Issue by rmaksim** [rgarcia/dochub#6]
no **: after** and **: before** in **CSS** - although it is present in the MDN.
https://developer.mozilla.org/en/CSS/%3Aafter
https://developer.mozilla.org/en/CSS/%3Abefore

and no **:first-letter** - https://developer.mozilla.org/en/CSS/%3A%3Afirst-letter

**Comment by rgarcia** [comment]
fixed by scraper commits on Dec 10. should be pushed to live soon...
