### ISSUE TITLE
model name mismatch on *nix OS

### ISSUE THREAD

**Issue by JiLiZART** [rgarcia/dochub#9]
https://github.com/rgarcia/instacss/blob/master/static/js/collections/phpexts.js#L5
app try to search SectionScrape.js, but sectionscrape.js in models folder

**Comment by JiLiZART** [comment]
this issue same as https://github.com/rgarcia/instacss/issues/8

**Comment by rgarcia** [comment]
right now the php collection isn't being used, so this code isn't getting hit.

**Comment by JiLiZART** [comment]
but they still loaded
